import {
  BngGameStatus,
  EvolutionGameStatus,
  FastSpinGameStatus,
} from "./ConfigGameStatus";

export const Game = {
  QQPK: {
    name: "QQPK",
    cp_key: 84,
    key: "dbd549fba180d58e0b6e0b3598258321",
    secret_key: "b8d96786dd52a797",
    agent_code: "1021202505071",
    url: "http://qa1.h5_open_api.nqsf9emow.com:27799/",
    img_url: "",
    call_url: "https://qqpk.enjoycx.com",
    req_call_timeout: 3000,
    game_type: "board",
    trans_stored: {
      round: 86400,
      bet_trans: 43200,
      result_trans: 43200,
      tip_trans: null,
      withdraw_trans: 86400,
      deposit_trans: 86400
    },
    language: {
      ko: "ko-KO", // 한국어 아직 비 지원
      en: "en-us",
      jp: "ja",
    },
    language_def: "ko",
    currency_type: ["KRW"],
    child_server_ip: ["127.0.0.1"],
    degit: 2,
  },
  FASTSPIN: {
    name: "FastSpin",
    cp_key: 85,
    url: "http://api.fastspinzone.com/api/",
    img_url: "",
    call_url: "",
    game_type: "SLOT",
    wallet: "SEAMLESS",
    req_call_timeout: 3000,
    trans_stored: {
      ROUND: 86400,
      BET_TRANS: 43200,
      RESULT_TRANS: 43200,
      TIP_TRANS: 43200,
    },
    language: {
      KO: "KO",
      EN: "EN",
    },
    language_def: "KO",
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
    },
    bet_limit_def: "1",
    degit: 2,
    secret_key: "VEDASFTXX01J8sRE2JsmWwt",
    merchant_code: "VEDASFT",
  },
  DEF: {
    name: "CX",
    cp_key: 0,
  },
  Evolution: {
    name: "Evolution",
    prov_code: "evolution",
    cp_key: 1,
    key: "subvgbcr30000001",
    api_token: "test123",
    lobby_token: "test123",
    history_token: "test123",
    use_trans_log: false,
    game_type: "live",
    url: "https://babylonvg.uat1.evo-test.com/",
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
    },
    bet_limit_def: "1",
    language_def: "ko",
    trans_stored: {
      ROUND: 259200,
      BET_TRANS: 21600,
      RESULT_TRANS: 21600,
      TIP_TRANS: 1800,
    },
    req_call_timeout: 5000,
    degit: 2,
  },
  CQ9: {
    name: "CQ9",
    cp_key: 4,
    digit: 4,
  },
  CQ9_LIVE: {
    name: "CQ9 Live",
    cp_key: 5,
    digit: 4,
  },
  CQ9_LIVE_MOTIVATION: {
    name: "Motivation",
    cp_key: 63,
    digit: 4,
  },
  CQ9_GROUP: {
    name: "CQ9 GROUP",
    cp_key: 105,
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2MjZhNjExM2JjMDg5NjAwMDE2YTIzZDQiLCJhY2NvdW50IjoidmVkYV9zdyIsIm93bmVyIjoiNjI2YTYxMTNiYzA4OTYwMDAxNmEyM2Q0IiwicGFyZW50Ijoic2VsZiIsImN1cnJlbmN5IjoiS1JXIiwianRpIjoiMjE5NDE0ODg0IiwiaWF0IjoxNjUxMTM4ODM1LCJpc3MiOiJDeXByZXNzIiwic3ViIjoiU1NUb2tlbiJ9.EzHX8g5OmjpkQ0rpHr72u6jLYUZbQTMTbf9z6jgHAuw",
    url: "https://api.cqgame.games/",
    call_url: "http://cq9.enjoycx.com",
  },
  PP: {
    name: "PragmaticPlay",
    cp_key: 7,
    pid: "veda_vedatest",
    // PID: "veda_vedatestbt",
    key: "testKey",
    // KEY: "32A43495C15542Bf",
    url: "https://api.prerelease-env.biz/",
    img_url: "https://api.prerelease-env.biz/",
    call_url: "http://pp.enjoycx.com",
    studio: "PP",
    game_type: "slot",
    wallet: "seamless",
    req_call_timeout: 5000,
    trans_stored: {
      round: 86400,
      bet_trans: 43200,
      result_trans: 43200,
      tip_trans: 43200,
    },
    language: {
      ko: "ko",
      en: "en",
    },
    language_def: "ko",
  },
  // PP_2: Game.PP,
  // PP_101: Game.PP,
  PP_BT: {
    name: "PragmaticPlay BT",
    cp_key: 1007,
    pid: "veda_vedatestbt",
    key: "32A43495C15542Bf",
    url: "https://api.prerelease-env.biz/",
    img_url: "https://api.prerelease-env.biz/",
    call_url: "http://pp.enjoycx.com",
    studio: "PP",
    game_type: "slot",
    wallet: "transfer",
    req_call_timeout: 5000,
    language: {
      ko: "ko",
      en: "en",
    },
    language_def: "ko",
  },
  PP_LIVE: {
    name: "PragmaticPlay",
    cp_key: 33,
    pid: "veda_vedatest",
    key: "testKey",
    url: "https://api.prerelease-env.biz/",
    img_url: "https://api.prerelease-env.biz/",
    call_url: "http://pp.enjoycx.com",
    studio: "PP",
    game_type: "live",
    wallet: "seamless",
    bet_limit: {
      A: "veda_A",
      B: "veda_B",
      C: "veda_C",
      D: "veda_D",
      E: "veda_E",
    },
    language_def: "ko",
    degit: 2,
    bet_limit_def: "veda_C",
    req_call_timeout: 5000,
  },
  PP_REELKINGDOM: {
    name: "Rell Kingdom",
    cp_key: 52,
    studio: "PP",
    game_type: "slot",
    req_call_timeout: 0,
  },
  PP_FATPANDA: {
    name: "FatPanda",
    cp_key: 83,
    pid: "veda_vedatest",
    key: "testKey",
    url: "https://api.prerelease-env.biz/",
    img_url: "https://api.prerelease-env.biz/",
    call_url: "http://pp.enjoycx.com",
    studio: "FP",
    game_type: "slot",
    wallet: "seamless",
    req_call_timeout: 5000,
  },
  DG: {
    name: "DreamGame",
    cp_key: 8,
    pid: "DGTE01072O",
    key: "c5c330c00a4e4f1bb02a26388d7da16f",
    fix: "Q9B",
    url: "http://api.dg99web.com/",
    game_data_url: "https://ag.dg66.info/",
    call_url: "http://dg.enjoycx.com",
    bet_limit_value: {
      "1": { min: 4000, max: 9000000 },
      "2": { min: 2000, max: 200000 },
      "3": { min: 2000, max: 400000 },
      "4": { min: 4000, max: 400000 },
      "5": { min: 4000, max: 800000 },
      "6": { min: 4000, max: 2000000 },
      "7": { min: 4000, max: 4000000 },
      "8": { min: 1000, max: 150000 },
      "9": { min: 30000, max: 300000 },
      "10": { min: 100000, max: 1000000 },
      "11": { min: 300000, max: 3000000 },
      "12": { min: 40000, max: 10000000 },
      "13": { min: 50000, max: 3000000 },
      "14": { min: 100000, max: 5000000 },
      "15": { min: 40000, max: 10000000 },
      "16": { min: 60000, max: 15000000 },
      "17": { min: 1200, max: 3000000 },
      "18": { min: 2000, max: 5000000 },
      "19": { min: 40000, max: 10000000 },
      "20": { min: 1000, max: 1000000 },
      "21": { min: 80000, max: 20000000 },
      "22": { min: 120000, max: 30000000 },
    },
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
      D: "4",
      E: "5",
      F: "6",
      G: "7",
      H: "8",
      I: "9",
      J: "10",
      K: "11",
      L: "12",
      M: "13",
      N: "14",
      O: "15",
      P: "16",
      Q: "17",
      R: "18",
      S: "19",
      T: "20",
      U: "21",
      V: "22",
    },
    bet_limit_def: "18",
    language: {
      ko: "kr",
      en: "en",
    },
    language_def: "kr",
    req_call_timeout: 0,
  },
  BNG: {
    name: "BNG",
    cp_key: 9,
    url: "HTTP://LOCALHOST:3000",
    img_url: "",
    call_url: "",
    studio: "BNG",
    game_type: "SLOT",
    wallet: "SEAMLESS",
    req_call_timeout: 1000,
    trans_stored: {
      round: 86400,
      bet_trans: 43200,
      result_trans: 43200,
      tip_trans: 43200,
    },
    language: {
      KO: "KO",
      EN: "EN",
    },
    language_def: "KO",
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
    },
    bet_limit_def: "1",
    degit: 2,
  },
  BNG_PLAYSON: {
    name: "Playson",
    cp_key: 23,
    req_call_timeout: 1000,
  },
  WM_LIVE: {
    name: "WM Live",
    cp_key: 12,
    pid: "vedaswapi",
    key: "19e1dc4a5059191f8c49b34777e0661e",
    url: "https://api.a45.me/api/wallet/Gateway.php",
    call_url: "http://wml.enjoycx.com",
    language: {
      ko: 5,
      en: 1,
    },
    language_def: 5,
    voice_def: "ko",
  },
  NetEnt: {
    name: "Netent",
    prov_code: "netent",
    cp_key: 20,
    game_type: "slot",
    language_def: "ko",
  },
  RedTiger: {
    name: "RedTiger",
    prov_code: "redtiger",
    cp_key: 22,
    game_type: "slot",
    language_def: "ko",
  },
  NoLimitCity: {
    name: "NLC",
    prov_code: "nlc",
    cp_key: 42,
    game_type: "slot",
    language_def: "ko",
  },
  BTG: {
    name: "BigTime Gaming",
    prov_code: "btg",
    cp_key: 56,
    game_type: "slot",
    language_def: "ko",
  },
  NextSpin: {
    name: "NextSpin",
    cp_key: 30,
    key: "zhpyd96vctytu7zl",
    api_token: "0794e7e8392ecffa5bf1398a3060bd62",
    url: "http://service-stage.klonostek.com/ns/",
    language_def: "ko",
  },
  PlayStar: {
    name: "PlayStar",
    cp_key: 24,
    pid: "ae0de5c0779a5fc89b81af764e38274e",
    token: "258907e9189382c61Af0e6cE5A486490e09278fAa3fCc542d0fBf252cB8C80a7",
    key: "",
    api_url: "https://stage-api.iplaystar.net/",
    history_url: "https://veda-admin.claretfox.com/Resource/game_history/",
  },
  PNG: {
    name: "PLAY'n Go",
    cp_key: 26,
    pid: "1193",
    KEY: "",
    URL: "https://asistage.playngonetwork.com/",
    API_URL: "https://api-stage-as.playngonetwork.com/",
  },
  PG: {
    name: "PG Soft",
    cp_key: 37,
    pid: "a7844843224fa1e5ff40c5918f393450",
    key: "1f65f6036a67d8f672663a74f15c6ca7",
    key_salt: "4823d7949356c7b59c1fcf5b2ce1a298",
    url: "https://api.pg-bo.me/external/",
    game_data_url: "https://api.pg-bo.me/external-datagrabber/",
    public_url: "https://public.pg-redirect.net/",
    launch_url: "https://api.pg-bo.me/",
    get_url: "http://out_cp-pg.enjoycx.com/get/url/",
    call_url: "http://pg.enjoycx.com",
    game_code_fix: "PG",
  },

  TG: {
    cp_key: 28,
    name: "TG",
    pid: "royalapi",
    key: "03d67912a568255f19776aeb72ea6d8940e7b72a624d1f05341e11d1c16f304f",
    url: "https://purplesapi.com/api/",
    call_url: "http://tg.enjoycx.com",
    fix: "stg",
    log_type: 2,
    bet_limit_value: {
      "1": {
        min: 100000,
        max: 10000000,
        tie_min: 10000,
        tie_max: 1250000,
        pair_min: 10000,
        pair_max: 900000,
      },
      "2": {
        min: 100000,
        max: 20000000,
        tie_min: 10000,
        tie_max: 2500000,
        pair_min: 10000,
        pair_max: 1800000,
      },
      "3": {
        min: 200000,
        max: 30000000,
        tie_min: 20000,
        tie_max: 3500000,
        pair_min: 20000,
        pair_max: 2600000,
      },
      "4": {
        min: 30000,
        max: 5000000,
        tie_min: 3000,
        tie_max: 600000,
        pair_min: 3000,
        pair_max: 450000,
      },
      "5": {
        min: 50000,
        max: 10000000,
        tie_min: 5000,
        tie_max: 1250000,
        pair_min: 5000,
        pair_max: 900000,
      },
    },
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
      D: "4",
      E: "5",
    },
    bet_limit_def: "1",
  },
  TG_STELLA: {
    cp_key: 82,
    name: "Stella",
    pid: "royalapi",
    key: "03d67912a568255f19776aeb72ea6d8940e7b72a624d1f05341e11d1c16f304f",
    url: "https://purplesapi.com/api/",
    call_url: "http://stella.enjoycx.com",
    fix: "stg",
    log_type: 2,
    bet_limit_value: {
      "1": {
        min: 100000,
        max: 10000000,
        tie_min: 10000,
        tie_max: 1250000,
        pair_min: 10000,
        pair_max: 900000,
      },
      "2": {
        min: 100000,
        max: 20000000,
        tie_min: 10000,
        tie_max: 2500000,
        pair_min: 10000,
        pair_max: 1800000,
      },
      "3": {
        min: 200000,
        max: 30000000,
        tie_min: 20000,
        tie_max: 3500000,
        pair_min: 20000,
        pair_max: 2600000,
      },
      "4": {
        min: 30000,
        max: 5000000,
        tie_min: 3000,
        tie_max: 600000,
        pair_min: 3000,
        pair_max: 450000,
      },
      "5": {
        min: 50000,
        max: 10000000,
        tie_min: 5000,
        tie_max: 1250000,
        pair_min: 5000,
        pair_max: 900000,
      },
    },
    bet_limit: {
      A: "1",
      B: "2",
      C: "3",
      D: "4",
      E: "5",
    },
    bet_limit_def: "1",
  },
  AG: {
    cp_key: 29,
    name: "Asia Gaming",
    digit: 4,
    bet_limit: {
      A: "A",
      B: "B",
      C: "C",
      D: "D",
      E: "E",
      F: "F",
      G: "G",
      H: "H",
      I: "I",
    },
    bet_limit_def: "C",
  },
  AG_SLOT: {
    cp_key: 30,
    name: "AG",
    digit: 4,
  },
  AG_GROUP: {
    cp_key: 106,
    name: "AG GROUP",
    pid: "JP6_AGIN",
    prud_id: "JP6",
    key_md5: "jp6CTjCsyjs9",
    key_des: "jp6SwgBJ",
    act: 1, //	0: trial, 1: real
    url: "http://gi.aggdemo.com:81/",
    game_url: "http://gci.aggdemo.com:81/",
    url_session: "https://swapi.etwlt.com/",
    call_url: "http://ag.enjoycx.com",
    id_length: 5,
    prefix: "stg",
    language: {
      ko: 5,
      en: 3,
    },
    language_def: 5,
  },
  Habanero: {
    name: "Habanero",
    cp_key: 25,
    pid: "aa79db7c-8d91-ed11-9d7a-00224819278b",
    key: "4B60A1BD-1F38-4345-AF51-D91C157785B9",
    url: "https://ws-test.insvr.com/jsonapi/",
    game_url: "https://app-test.insvr.com/go.ashx",
    history_url: "https://app-test.insvr.com/games/history/",
    call_url: "http://habanero.enjoycx.com",
  },
  Sports: {
    name: "Sports",
    cp_key: 32,
    url: "https://api.tsp-staging.com/",
    call_url: "http://sports.enjoycx.com",
  },
  Taishan: {
    name: "Taishan",
    cp_key: 51,
    pid: "royalclub",
    key: "a13579!@#",
    url: "https://g5.nts3000.com/API/",
    call_url: "http://taishan.enjoycx.com",
    fix: "stg",
    req_call_timeout: 5000,
  },
  Dowin: {
    name: "Dowin",
    cp_key: 53,
    pid: "swix_test",
    key: "fb7a73eadfb346fd9852c91249424c69",
    url: "http://stage.dwclub6789.com:9000/",
    call_url: "http://dowin.enjoycx.com",
    digit: 4,
    fix: "stg",
    bet_limit_value: {
      "1": {
        bet_n_min: 5000,
        bet_n_max: 20000,
        bet_t_min: 5000,
        bet_t_max: 25000,
        bet_r_min: 5000,
        bet_r_max: 28000,
      },
      "2": {
        bet_n_min: 30000,
        bet_n_max: 50000,
        bet_t_min: 20000,
        bet_t_max: 30000,
        bet_r_min: 10000,
        bet_r_max: 20000,
      },
    },
    bet_limit: {
      A: "1",
      B: "2",
    },
    bet_limit_def: "1",
    language: {
      ko: "KO",
      en: "EN",
      jp: "JP",
    },
    language_def: "KO",
  },
  MGP: {
    name: "MicroGaming Plus",
    prov_code: "microgamingplus",
    cp_key: 54,
    game_type: "live",
  },
  MGP_GRAND: {
    name: "MicroGaming Plus Grand",
    prov_code: "microgamingplusgrand",
    cp_key: 67,
    game_type: "live",
  },
  MGP_SLOT: {
    name: "MicroGaming Plus Slot",
    prov_code: "microgamingplusslot",
    cp_key: 55,
    game_type: "slot",
    lobby_gamecode: "falconlobby",
  },
  MOA_EVOLUTION: {
    name: "Evolution",
    cp_key: 1,
    game_type: "live",
  },
  MOA_EVOPLAY: {
    name: "Evoplay",
    cp_key: 3,
    game_type: "slot",
  },
  MOA_YGG: {
    name: "Yggdrasil",
    cp_key: 6,
    game_type: "slot",
  },
  MOA_PP: {
    name: "PragmaticPlay",
    cp_key: 7,
    game_type: "slot",
  },
  MOA_BNG: {
    name: "Booongo",
    cp_key: 9,
    game_type: "slot",
  },
  MOA_RTG: {
    name: "Real Time Gameing",
    cp_key: 10,
    game_type: "slot",
  },
  MOA_QUICKSPIN: {
    name: "Quick Spin",
    cp_key: 16,
    game_type: "slot",
  },
  MOA_WAZDAN: {
    name: "Wazdan",
    cp_key: 17,
    game_type: "slot",
  },
  MOA_NETENT: {
    name: "Netent",
    cp_key: 20,
    game_type: "slot",
  },
  MOA_EZUGI: {
    name: "Ezugi",
    cp_key: 21,
    game_type: "live",
  },
  MOA_REDTIGER: {
    name: "Red Tiger",
    cp_key: 22,
    game_type: "slot",
  },
  MOA_HABANERO: {
    name: "Habanero",
    cp_key: 25,
    game_type: "slot",
  },
  MOA_PLAYNGO: {
    NAME: "PlayNGo",
    cp_key: 26,
    game_type: "slot",
  },
  MOA_RELAX: {
    name: "Relax Gaming",
    cp_key: 27,
    game_type: "slot",
  },
  MOA_PPL: {
    name: "PragmaticPlay Live",
    cp_key: 33,
    game_type: "live",
  },
  MOA_TRIPLEPG: {
    name: "Triple Profit Gaming",
    cp_key: 34,
    game_type: "slot",
  },
  MOA_GAMEART: {
    name: "GameArt",
    cp_key: 35,
    game_type: "slot",
  },
  MOA_BLUEPRINT: {
    name: "Blueprint Gaming",
    cp_key: 40,
    game_type: "slot",
  },
  MOA_THUNDERKICK: {
    name: "Thunderkick",
    cp_key: 41,
    game_type: "slot",
  },
  MOA_NOLIMITCITY: {
    name: "Nolimit City",
    cp_key: 42,
    game_type: "slot",
  },
  MOA_MOBILOTS: {
    name: "Mobilots",
    cp_key: 43,
    game_type: "slot",
  },
  MOA_PLAYPEARLS: {
    name: "PlayPearls",
    cp_key: 44,
    game_type: "slot",
  },
  MOA_DRAGOONSOFT: {
    name: "Dragoon Soft",
    cp_key: 45,
    game_type: "slot",
  },
  MOA_BETGAMESTV: {
    name: "Betgames.tv",
    cp_key: 46,
    game_type: "live",
  },
  MOA_SKYWINDLIVE: {
    name: "Skywind Live",
    cp_key: 47,
    game_type: "live",
  },
  MOA_SKYWINDCASINO: {
    name: "Skywind Casino",
    cp_key: 64,
    game_type: "slot",
  },
  MOA_1X2: {
    name: "1X2 Gaming",
    cp_key: 49,
    game_type: "slot",
  },
  MOA_ELK: {
    name: "Elk Studios",
    cp_key: 50,
    game_type: "slot",
  },
  MOA_VIVO: {
    name: "Vivo Gaming",
    cp_key: 13,
    game_type: "live",
  },
  MOA_ONLYPLAY: {
    name: "Onlyplay",
    cp_key: 65,
    game_type: "slot",
  },
  AllBet: {
    cp_key: 48,
    name: "ALLBET",
    pid: 4323472,
    key: "KZ/uC1c9g9kdB89DL4uiVHJdTI8dYWmBjU37pX2sk3TTOJRuWvnT54PblDWvkrF6tWkdarF9lz4hLthXHkDWtA==",
    url: "https://sw2.apidemo.net:8443/",
    call_url: "http://allbet.enjoycx.com",
  },
  KD: {
    cp_key: 57,
    name: "KD",
    pid: "VEDA_STAGING",
    key: "11d2ba94d135491a8e0615956add8c9f",
    url: "https://api.kd-vd-dev.com/",
    call_url: "http://kd.enjoycx.com",
    language_def: "ko",
  },
  DC_EVOPLAY: {
    name: "Evoplay",
    cp_key: 3,
    game_type: "slot",
  },
  DC_YGG: {
    name: "Yggdrasil",
    cp_key: 6,
    game_type: "slot",
  },
  DC_PNG: {
    name: "PLAY'n Go",
    cp_key: 26,
    game_type: "slot",
  },
  DC_RELAX: {
    name: "Relax Gaming",
    cp_key: 27,
    game_type: "slot",
  },
  DC_AVATARUX: {
    name: "Avatarux",
    cp_key: 58,
    game_type: "slot",
  },
  DC_HACKSAW: {
    name: "Hacksaw",
    cp_key: 59,
    game_type: "slot",
  },
  DC_OCTOPLAY: {
    name: "Octoplay",
    cp_key: 77,
    game_type: "slot",
  },
  DC_NOVOMATIC: {
    name: "Novomatic",
    cp_key: 79,
    game_type: "slot",
  },
  DC_BGAMING: {
    name: "BGaming",
    cp_key: 80,
    game_type: "slot",
  },
  DC_BLUEPRINT: {
    name: "Blueprint Gaming",
    cp_key: 40,
    game_type: "slot",
  },
  DC_THUNDERKICK: {
    name: "Thunderkick",
    cp_key: 41,
    game_type: "slot",
  },
  VIVO: {
    name: "VIVO",
    cp_key: 13,
    pid: "veda",
    key: "7f1c5d",
    url: "http://games.vivogaming.com/",
    call_url: "http://vivo.enjoycx.com",
  },
  PlayTech: {
    name: "PlayTech Live",
    cp_key: 60,
    game_type: "live",
  },
  PlayTech_slot: {
    name: "PlayTech Slot",
    cp_key: 61,
    game_type: "slot",
  },
  BTI: {
    name: "BTI",
    cp_key: 62,
    pid: "111111",
    key: "",
    url: "https://stg20272-120914874.4x4x2.dev/ko/korean-view",
    call_url: "https://bti.enjoycx.com",
    game_type: "sports",
    bet_limit_def: "A",
    trans_stored: {
      ttl: {
        round: 172800,
        bet_trans: 172800,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
  },
  WildGames: {
    name: "WildGames",
    cp_key: 63,
    pid: "43445d939d",
    key: "a145dc61-202c-46c1-b4e7-9a9daf3e324c",
    url: "https://iapi-v1.wildfreegames.com/v1/http/",
    call_url: "http://hold.enjoycx.com",
    trans_stored: {
      ttl: {
        round: 172800,
        bet_trans: 172800,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
    digit: 0,
  },
  ASTAR: {
    name: "ASTAR",
    prov_code: "astar",
    cp_key: 66,
    pid: "VEDA",
    token: "78f95b7d-1d38-49e5-b49e-6617153ebfe3",
    key: "3a48ac34-86ea-46db-ab7e-0d0709d71773",
    url: "https://astar111.com/",
    log_view_url: "https://api.astar66.com/",
    call_url: "http://astar.enjoycx.com",
    time_zone: -4,
  },
  AWC_SEXY: {
    name: "Sexy Casino",
    cp_key: 36,
    game_type: "live",
    digit: 3,
    bet_limit: {
      A: "280801",
      B: "280802",
      C: "280803",
      D: "280804",
      E: "280805",
      F: "280806",
    },
    bet_limit_def: "280801",
    trans_stored: {
      ttl: {
        round: 172800,
        bet_trans: 172800,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
  },
  FC: {
    name: "FC Game",
    prov_code: "fc",
    cp_key: 68,
    pid: "VEDA",
    key: "pOg91aLPPA2AHNHN",
    url: "https://api.fcg666.net/",
    call_url: "http://fc.enjoycx.com",
    language: {
      ko: 8,
      en: 1,
      jp: 7,
    },
    language_def: 8,
  },
  JDB_JDB: {
    name: "JDB",
    prov_code: "jdb",
    cp_key: 69,
    game_type: "slot",
    paymode: "BetNSettle",
  },
  JDB_HRG: {
    name: "HRG",
    prov_code: "hrg",
    cp_key: 72,
    game_type: "live",
    paymode: "PrepayBet",
    bet_limit: {
      A: "800001",
      B: "800006",
      C: "800007",
      D: "800008",
      E: "800009",
    },
    bet_limit_def: "800001",
  },
  DBCasino: {
    name: "DB Casino",
    prov_code: "dbcasino",
    cp_key: 70,
    pid: "AFBF7",
    key: "mvWT9zuZtXOEY7r1",
    key_md5: "edXhEUF26R1cGaXu",
    key_data_md5: "BlXryk8ISTQ9Ho1E",
    url: "https://api.obothapi.com/",
    history_url: "https://api-data.obothapi.com/",
    call_url: "http://dbcasino.enjoycx.com",
    digit: 4,
    req_call_timeout: 2500,
    language: {
      ko: 5,
      en: 3,
      jp: 4,
    },
    language_def: 5,
  },
  HiddenPoker: {
    name: "Hidden Poker",
    prov_code: "hiddenpoker",
    cp_key: 71,
    pid: "hdpk",
    key: "ingMVfJENGTPFp2dtqrCw4VDTD8m5BbH",
    url: "http://54.151.190.58:8110/",
    call_url: "http://hdpk.enjoycx.com",
    game_type: "board",
  },
  BG: {
    name: "Big Gaming",
    cp_key: 73,
    pid: "sc06",
    key: "8153503006031672EF300005E5EF6AEF",
    url: "http://openapi-uat.feiyanma.com/open-cloud/api/",
    img_url: "",
    call_url: "http://bg.enjoycx.com",
    // CALL_URL			: "http://127.0.0.1:11001",
    req_call_timeout: 5000,
    game_type: "live",
    agent_id: "demoagent",
    agent_pwd: "123456asdfgh",
    trans_stored: {
      ttl: {
        round: 86400,
        bet_trans: 43200,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
    language: {
      ko: "ko_KR",
      en: "en_US",
      jp: "ja_JP",
    },
    language_def: "ko_KR",
    child_server_ip: ["127.0.0.1"],
  },
  HRG: {
    name: "Hot Road Gaming",
    cp_key: 72, // 기존 HRG 코드 사용
    pid: "t4zhwyesuikSdWL7F9EWAe35danBHZxnSM",
    key: "qmzida9GHV5CAs7iEaJqMByuJcSHpGyeCN",
    url: "https://api.demohotroadgaming.com/api/",
    img_url: "",
    call_url: "http://hrg.enjoycx.com",
    // CALL_URL   : "http://127.0.0.1:11001",
    req_call_timeout: 5000,
    game_type: "live",
    agent_id: "vedastgkrwag",
    trans_stored: {
      ttl: {
        round: 86400,
        bet_trans: 43200,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
    language: {
      ko: "KR",
      en: "EN",
      jp: "JP",
    },
    language_def: "KR",
    child_server_ip: ["127.0.0.1"],
    result_code: {
      SUCCESS: "0000",
      BET_FAIL: "8001",
      FAIL: "9999",
    },
    bet_limit: {
      A: "800001", // 500 - 100000
      B: "800002", // 2500 - 250000
      C: "800003", // 5000 - 500000
      D: "800004", // 12500 - 125000
      E: "800005", // 20000 - 2000000
      F: "800006", // 1000 - 3000000
      G: "800007", // 1000 - 5000000
      H: "800008", // 1000 - 10000000
      I: "800009", // 1000 - 30000000
      J: "800010", // 1000 - 50000000
      K: "800011", // 100 - 3000000
      L: "800012", // 100 - 5000000
      M: "800013", // 100 - 10000000
      N: "800014", // 200 - 30000000
      O: "800015", // 500 - 50000000
    },
  },
  SC: {
    name: "Sky City",
    cp_key: 74,
    key: "e81c8b7d00284b0a8bad3a43fbfeb36e",
    url: "https://gameapi.skycityghub.com/op/api/seamless/",
    img_url: "",
    call_url: "http://sc.enjoycx.com",
    // CALL_URL			: "http://127.0.0.1:11001",
    req_call_timeout: 5000,
    game_type: "sports",
    trans_stored: {
      ttl: {
        round: 172800,
        bet_trans: 172800,
        result_trans: 43200,
        tip_trans: 43200,
      },
    },
    language: {
      ko: "KR",
      en: "EN",
      jp: "JP",
    },
    language_def: "KR",
    child_server_ip: ["127.0.0.1"],
    result_code: {
      SUCCESS: 0,
      FAIL: 1,
    },
    result_err_msg: {
      NOT_ENOUGH: "F01",
      ERROR: "F02",
      MEMBER: "F99",
    },
  },
  Oddin: {
    name: "Oddin",
    cp_key: 75,
    key: "a4b123bb-4472-4269-9d93-dc78536f455d",
    url: "https://iframe.integration.fulla.bet",
    url_script: "https://iframe.integration.fulla.bet/script.js",
    call_url: "https://oddin.enjoycx.com",
    out_url: "https://out_oddin.enjoycx.com",
    language: {
      ko: "ko",
      en: "en",
    },
    language_def: "ko",
  },
  SB: {
    name: "Saba",
    cp_key: 76,
    key: "te1wqrir9j",
    op_key: "VedaSoft",
    prefix: "",
    url: "https://k007tsa.bw6688.com/api/",
    img_url: "",
    call_url: "http://sb.enjoycx.com",
    req_call_timeout: 5000,
    game_code: "saba",
    game_type: "sports",
    game_type_mini: "minigame",
    trans_stored: {
      ttl: {
        round: 60 * 60 * 24 * 8,
        bet_trans: 60 * 60 * 24 * 8,
        result_trans: 60 * 60 * 24 * 8,
        tip_trans: 0,
      },
    },
    language: {
      ko: "ko",
      en: "en",
      jp: "jp",
    },
    language_def: "KR",
    child_server_ip: ["127.0.0.1"],
    result_code: {
      UNDEFINED: -1,
      SUCCESS: 0,
      DULICATE_TRANSACTION: 1,
      PARAMS_ERROR: 101,
      ACOUNT_CLOSED: 201,
      ACOUNT_LOCKED: 202,
      ACOUNT_IS_NOT_EXIST: 203,
      ACOUNT_SUSPENDED: 204,
      ACOUNT_EXISTED: 205,
      MERCHANT_ID_IS_NOT_EXIST: 301,
      INVALID_CURRENCY: 302,
      INVALID_USER_ID: 303,
      LANG_IS_NOT_SUPPORT: 304,
      INVALID_TOKEN: 305,
      INVALID_TIMEZONE: 306,
      INVALID_AMOUNT: 307,
      INVALID_DATETIME_FORMAT: 308,
      INVALID_TRANS_STATUS: 309,
      INVALID_BET_LIMIT_SETTING: 310,
      INVALID_AUTH_KEY: 311,
      INVALID_IP: 312,
      PERMISSION_DENIED: 501,
      PLAYER_HAS_INSUFFICIENT_FUND: 502,
      IP_RESTRICED: 503,
      NO_SUCH_TICKET: 504,
      NO_DATA: 505,
      UNABLE_TO_PROCESS: 506,
      BET_NOT_ELIGIBLE: 507,
      PLACEBET_CANNOT_BE_RETRIED: 508,
      DATABASE_ERROR: 901,
      NETWORK_ERROR: 902,
      MAINTENANCE: 903,
      REQUEST_TIMEOUT: 904,
      SYSTEM_BUSY: 905,
      SYSTEM_ERROR: 999,
    },
    time_zone: -4,
    odds_type: 3,
    currency_type: 20, //STG는 20의 값만 사용.
    max_bet_limit: 1000000,
    min_bet_limit: 1000,
    platform: {
      PC: 1,
      MOBILE: 2,
    },
    log_path: "/extraDisk/developer0004/log",
    job_path: "/home/developer0004/source/veda-api/jobs/sb_jobs.js",
  },
  SA: {
    name: "SA",
    cp_key: 78,
    encryption_key: "g9G16nTs",
    md5_key: "GgaIMaiNNtg",
    secret_key: "5591C0786C4B40B78F62BB66C8B12F90",
    lobby_code: "A11809",
    prefix: "",
    url: "https://sai-api.sa-apisvr.com/api/api.aspx",
    game_url: "https://www.sai.slgaming.net/app.aspx",
    img_url: "",
    call_url: "http://sa.enjoycx.com",
    req_call_timeout: 3000,
    game_type: "live", // slot?
    trans_stored: {
      ttl: {
        round: 60 * 60 * 24 * 2,
        bet_trans: 60 * 60 * 24 * 2,
        result_trans: 60 * 60 * 24 * 2,
        tip_trans: 0,
      },
    },
    language: {
      ko: "ko",
      en: "en-us",
      jp: "ja",
    },
    language_def: "ko",
    currency_type: ["KRW"],
    child_server_ip: ["127.0.0.1"],
    result_code: {
      SUCCESS: 0,
      USER_ACCOUNT_DOESNT_EXIST: 1000,
      INVALID_CURRENCY: 1001,
      INVALID_AMOUNT: 1002,
      LOCKED_ACCOUNT: 1003,
      INSUFFICIENT_BALANCE: 1004,
      GENERAL_ERROR: 1005,
      DECRYPTION_ERROR: 1006,
      SESSION_EXPIRED_ERROR: 1007,
      SYSTEM_ERROR: 9999,
    },
  },
  CLP: {
    name: "Clot Play",
    cp_key: 81,
    key: "VDADDD2B833F3231",
    agent_code: "POPStest",
    prefix: "",
    url: "https://api-int.clotplay.com/api/MOGI/",
    img_url: "",
    call_url: "http://clp.enjoycx.com",
    req_call_timeout: 3000,
    game_type: "slot",
    // TRANS_STORED  : { TTL: { ROUND: 60 * 60 * 24 * 2, BET_TRANS: 60 * 60 * 24 * 2, RESULT_TRANS: 60 * 60 * 24 * 2, TIP_TRANS: 0 } },
    language: {
      ko: "en-us", // 한국어 아직 비 지원
      en: "en-us",
      jp: "ja",
    },
    language_def: "en",
    currency_type: ["KRW"],
    child_server_ip: ["127.0.0.1"],
    result_code: {
      fail: -1,
      success: 0,
      params_error: 1000,
      invalid_user_id: 1001,
      session_error: 1002,
    },
    platform: {
      pc: "landscape",
      mobile: "portrait",
    },
    log_path: "",
    job_path: "",
  },
};

export const Config = {
  EVOLUTION_GROUP: {
    name: "EVOLUTION GROUP",
    cp_key: 101,
    key: "babylonvg0000001",
    api_token: process.env.EVO_API_TOKEN || "test123",
    lobby_token: process.env.EVO_LOBBY_TOKEN || "test123",
    url: "https://babylonvg.uat1.evo-test.com/",
    call_url: "http://evolution.enjoycx.com",
    vendors: {
      1: Game.Evolution,
      20: Game.MOA_NETENT,
      22: Game.MOA_REDTIGER,
      42: Game.MOA_NOLIMITCITY,
      56: Game.BTG,
    },
    vendorsId: {
      netent: Game.MOA_NETENT,
    },
  },
  BNG_GROUP: {
    name: "BNG",
    cp_key: 102,
    pid: "swix-stage",
    key: "8qXCT7u3e8",
    brand: "swix-stage",
    url: "https://gate-stage.betsrv.com/op/",
    url_lobby: "https://bng.lobby3apservice.com/GamesCenter/",
    lobby_gamecode: "bnglobby",
    call_url: "http://bng.enjoycx.com",
    vendors: {
      "1": Game.BNG,
      "2": Game.BNG_PLAYSON,
      "4": Game.BNG,
    },
  },
  MGP_GROUP: {
    name: "MicroGaming Plus",
    cp_key: 108,
    pid: "Test_Veda_2_KRW",
    key: "d1c6b049-8f7e-44d2-932b-fee858127a77",
    key_scret: "936c359119db4b9a95573ab8cdce2b",
    url: "https://api-veda2sw.k2net.io/",
    token_url: "https://sts-veda2sw.k2net.io/",
    call_url: "http://mg.enjoycx.com",
    vendors: {
      LIVEDEALER: Game.MGP,
      LIVEDEALERGRAND: Game.MGP_GRAND,
      MGLGRANDLIVEDEALER: Game.MGP_GRAND,
      MICROGAMINGLIVE: Game.MGP_GRAND,
      SLOTS: Game.MGP_SLOT,
    },
  },
  MOA_GROUP: {
    name: "MOA",
    cp_key: 104,
    pid: "api_veda",
    key: "aammEhu8",
    passkey: "06f13ff7-9968-4705-9200-2c295520d0ce",
    url: "https://api-int.qtplatform.com/",
    call_url: "http://qtech.enjoycx.com",
    vendors_id: {
      // "EVO":		Game.MOA_EVOLUTION,
      // "YGG":		Game.MOA_YGG,
      // "PPC":		Game.MOA_PP,
      // "RTG":		Game.MOA_RTG,
      // "QS":		Game.MOA_QUICKSPIN,
      // "NE":		Game.MOA_NETENT,
      // "EZU":		Game.MOA_EZUGI,
      // "RED":		Game.MOA_REDTIGER,
      // "PPL":		Game.MOA_PPL,
      // "HAB":		Game.MOA_HABANERO,
      PNG: Game.MOA_PLAYNGO,
      EVP: Game.MOA_EVOPLAY,
      BNG: Game.MOA_BNG,
      WAZ: Game.MOA_WAZDAN,
      RLX: Game.MOA_RELAX,
      TPG: Game.MOA_TRIPLEPG,
      GA: Game.MOA_GAMEART,
      BPG: Game.MOA_BLUEPRINT,

      TK: Game.MOA_THUNDERKICK,
      NLC: Game.MOA_NOLIMITCITY,
      MOB: Game.MOA_MOBILOTS,
      PP: Game.MOA_PLAYPEARLS,
      DS: Game.MOA_DRAGOONSOFT,
      BTV: Game.MOA_BETGAMESTV,
      SWL: Game.MOA_SKYWINDLIVE,
      "1x2": Game.MOA_1X2,
      ELK: Game.MOA_ELK,
      VGL: Game.MOA_VIVO,
      SWC: Game.MOA_SKYWINDCASINO,
      OPY: Game.MOA_ONLYPLAY,
    },
  },
  GAMECODE: {
    NONE: "",
    SLOT: "slot",
    LIVE: "live",
    SPOOR: "sports",
    BORD: "board",
  },
  DC_GROUP: {
    cp_key: 109,
    name: "DC",
    pid: "S089002",
    key: "193C2044332242128E04F7FC4D6FAD67",
    url: "https://gaming.stagedc.net/",
    history_url: "https://ticket.stagedc.net",
    call_url: "http://dc.enjoycx.com",
    id_length: 20,
    vendors_id: {
      evo: Game.DC_EVOPLAY,
      yg: Game.DC_YGG,
      png: Game.DC_PNG,
      relax: Game.DC_RELAX,
      aux: Game.DC_AVATARUX,
      hs: Game.DC_HACKSAW,
      op: Game.DC_OCTOPLAY,
      nm: Game.DC_NOVOMATIC,
      bg: Game.DC_BGAMING,
      bp: Game.DC_BLUEPRINT,
      tk: Game.DC_THUNDERKICK,
    },
    vendors: {
      3: Game.DC_EVOPLAY,
      6: Game.DC_YGG,
      26: Game.DC_PNG,
      27: Game.DC_RELAX,
      58: Game.DC_AVATARUX,
      59: Game.DC_HACKSAW,
      77: Game.DC_OCTOPLAY,
      79: Game.DC_NOVOMATIC,
      80: Game.DC_BGAMING,
      40: Game.DC_BLUEPRINT,
      41: Game.DC_THUNDERKICK,
    },
  },
  PLAYTECH_GROUP: {
    name: "PlayTech",
    cp_key: 110,
    pid: "ptstaging3.33",
    key: "",
    prefix: "VEDA__",
    url: "https://extstg3-gameslink.ptstaging.eu/product/gameslink/service",
    launcher_url: "https://extstg3-login01.ptstaging.eu/GameLauncher",
    call_url: "http://playtech_swix.enjoycx.com",
    vendors: {
      // 60: PlayTech,
      // 61: PlayTech_slot
    },
  },
  AWC_GROUP: {
    NAME: "AWC",
    cp_key: 111,
    // PID					: "vadastaging",
    // KEY					: "pURgt7nAiJ7sNG3rtyU",
    // URL					: "https://tttint.onlinegames22.com/",
    pid: "agzala",
    key: "JzzQQOYNR2rauMzH5TC",
    url: "https://tttint.onlinegames22.com/",
    call_url: "https://awc.enjoycx.com",
    time_zone: 8,
    language: {
      ko: "kr",
      en: "en",
    },
    LANGUAGE_DEF: "kr",
    VENDORS: {
      68: Game.AWC_SEXY,
    },
  },
  JDB_GROUP: {
    name: "JDB",
    cp_key: 112,
    pid: "vedakrwag",
    dc: "VEDA",
    iv: "2b45ce6e5f7f6e0d",
    key: "a0fbe11b2e4e7490",
    prefix: "STG",
    url: "https://api.jdb711.com/",
    call_url: "http://jdb.enjoycx.com",
    language: {
      ko: "kor",
      en: "en",
      jp: "jpn",
    },
    language_def: "kor",
    vendors: {
      69: { ID: 0, CP: Game.JDB_JDB },
      72: { ID: 41, CP: Game.JDB_HRG },
    },
    vendors_id: {
      0: Game.JDB_JDB,
      41: Game.JDB_HRG,
    },
  },
  BET_EVENT_TYPE: {
    NORMAL: 0,
    EVENT_SPIN: 1,
    FREE_SPIN: 2,
    BONUS_SPIN: 3,
    JACKPOT: 4,

    CANCEL_RESULT: 70,
    EVENT_CASH: 100,
    EVENT_TOURNAMENT: 101,
    EVENT_TIP: 102,
    EVENT_CANCEL_TIP: 103,

    RESERVE: 140,
    DEBIT_RESERVE: 141,
    COMMIT_RESERVE: 142,
    CANCEL_RESERVE: 143,
    RESULT_DEBIT: 145,
    ADJUSTMENT_DEC: 150,
    ADJUSTMENT_ADD: 151,

    CASHWITHDRAW: 160,
    CASHDEPOSIT: 163,

    RESULT: {
      CORRECTION: 200,
      CHNAGE_WIN: 201,
      CHNAGE_LOST: 202,
      CORRECTION_ADD: 203,
      CORRECTION_DEC: 204,
      BET_PARTITIAL_REFUND: 205,
    },
  },
  bng_force_gamecode: {
    "299": { to_provider_id: "1" },
    "371": { to_provider_id: "1" },
    "378": { to_provider_id: "1" },
    "380": { to_provider_id: "1" },
    "279": { to_provider_id: "1" },
    "361": { to_provider_id: "1" },
    "176": { to_provider_id: "1" },
    "352": { to_provider_id: "1" },
    "294": { to_provider_id: "1" },
    "69": { to_provider_id: "1" },
    "373": { to_provider_id: "1" },
    "311": { to_provider_id: "1" },
    "205": { to_provider_id: "1" },
    "282": { to_provider_id: "1" },
    "264": { to_provider_id: "1" },
  },
  // src/config/config.ts
  APP_ENV: "location",
  // APP_PORT: 3000, // pm2 啟動, 需要由外部決定

  // business
  PROD: false,
  DEBUG: true,
  VER_MIN: 1,
  VER_MAX: 2,
  VER_DEFAULT: 2,
  MAX_OPERATOR_KEY_CODE_LENGTH: 3,
  MAX_OPERATOR_KEY_ADD_VALUE: 12000,
  ENC_KEY: "09caba193a924761a7ce523f10dd32b2",
  ENC_IV_LENGTH: 16,
  UNKNOWN_VALUE: -999999999,
  TIME_ZONE: 0,
  TIME_MS_OF_DAY: 86400000,
  TIME_MS_OF_HOUR: 3600000,
  TIME_MS_OF_MINUTE: 60000,
  RESPONSE_ERROR: "error",
  MAX_GAMECODE_LENGTH: 100,
  MAIN_APP_IP: [
    "10.0.0.21",
    "20.27.82.68",
    "20.27.239.108",
    "127.0.0.1",
    "::ffff:127.0.0.1",
    "::ffff:10.0.0.21",
  ],
  MANAGER_IP: ["20.27.82.68"],
  PRODUCT_NAME: "CX",
  MAIN_DOMAIN: "http://enjoycx.com/",
  MAIN_SERVER_URL: "http://smapi.enjoycx.com/",
  PLAY_API_URL: "http://127.0.0.1:9001/play",
  IMAGE_SERVER_URL: "https://vedaimg.enjoycx.com/",
  TRANSFER_SERVER_URL: "http://transfer01.enjoycx.com/",
  LOG_VIEW_SERVER_URL_SET: "https://logview.veda-sp.com/set.php",
  LOG_VIEW_SERVER_URL_GET: "https://logview.veda-sp.com/get.php",
  MAX_UUID_SIZE: 32,
  MAX_USER_KEY_SIZE: 6,
  MAX_USER_ID_PREFIX_LEN: 3,
  MAX_USER_ID_BODY_LEN: 9,
  MAX_CUSTOMER_VALUE_LEN: 20,
  DB_TIMECHECK_MS: 30,
  CALLBACK_TIMECHECK_MS: 100,
  MAX_TRANSFER_USER_DISPERSE_SIZE: 4,

  // ??
  OPERATOR_KEEP_MS: 900000,
  SEC_DAY: 86400,
  CALLBACK_REQUEST_TIMEOUT: 1500,
  BET_LIMIT_DEF: "A",
  LANGUAGE_DEF: "ko",
  COUNTRY_NO: 410,
  COUNTRY_A2: "KR",
  COUNTRY_A3: "KOR",
  GAME_USE_LIST_RELOAD_TIME: 60000,

  // Splash
  SPLASH_USE: true,
  SPLASH_DEF_NAME: "master",
  SPLASH_PLAY_API_URL: "http://20.27.239.108:9960/",

  // Public
  PUBLIC_URL_EXIT: "https://out_public.veda-sp.com/exit",
  SP_SERVER_URL: {
    GAMECODE: "https://game-code.veda-sp.com/",
  },
  SERVICE_LOG_SERVER: {
    URL: "http://20.27.239.108:8080/stream",
    type: {
      api_app_play: 100,
      api_play_play: 101,

      cp_req_svc: 1000,
      svc_req_op_res: 2000,
      r_log: 2001,
      svc_res_cp: 3000,
    },
  },
  // Wallet
  WALLET_TYPE: {
    SEAMLESS: "seamless",
    TRANSFER: "transfer",
  },

  // Currency
  CURRENCY: {
    DEF: "KRW",
    KOR: "KRW",
    EUR: "EUR",
    JPN: "JPY",
  },

  // Redis Connection
  REDIS: {
    HOST: "127.0.0.1",
    PORT: 8600,
    PASSWORD: "r2e3d4i5s6",
    DB: 0,
    TIMECHECK_MS: 20,
    SESSION_USE: true,
    BALANCE_USE: false,
    BALANCE_KEEP_SEC: 60,
    GAMELOG_USE: true,
    GAMELOG_KEEP_SEC: 21600,
    LIVE_ROUND_LOG_USE: true,
    LIVE_ROUND_LOG_KEEP_SEC: 864000,
    ROUND_CHECK_USE: true,
    ROUND_CHECK_KEEP_SEC: 43200,
    AUTHTOKEN_KEEP_USE: true,
    AUTHTOKEN_KEEP_SEC: 43200,
    IO_LOG_USE: true,
    IO_LOG_TTL_SEC: 259200,
    TRANSDATA_USE: true,
    TRANSDATA_KEEP_SEC: 6 * 60 * 60, // 6hr
    TRANSDATA_KEEP_SEC_MIN: 3600,
    TRANS_LOG_TOKEN_KEEP_SEC: 3600,
    TRANS_LOG_USE: true,
    GAME_USE_LIST_USE: true,
    GAME_USE_LIST_USE_KEEP_SEC: 86400,
  },

  // gRPC
  GRPC_SERVER_HOST: "10.0.0.191:50051",
  CA_CERT_PEM: `
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgIUBcpCYv4daI8+KtnE2EQsNZxxhgwwDQYJKoZIhvcNAQEL
BQAwHTEbMBkGA1UEAwwSY29yZS1zZXJ2aWNlLmxvY2FsMB4XDTI1MDkxNzA5NDgy
NloXDTM1MDkxNTA5NDgyNlowHTEbMBkGA1UEAwwSY29yZS1zZXJ2aWNlLmxvY2Fs
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5fIR8NqNmjMpjl2bd0oN
q9bueam2RsaHjekbPsROmlk94/s0RrG4jGFvKGSBQkK0mXVzkfI5ObsayNf5+PI5
ih2ydOywD14+S6KK3KhHOOFbz9VTN8Rn7HMWDRMyEW36vqwwoNeZ/kwQXPoXIRtg
EhCzqKdMECbY8PWJDd0vC5k2TlqhqZsOfmICORoZMgSsSBm6j5rDIg0VTLa75Ofa
DNc2wvZW2bthVlrhRXQKfIeyG4t/saTulpeDotf3wgyOZRIJtQP6N7hGDH/rXMo+
Ey/clthjYaL7CRWtSdlYa0WODbNJ6snbsyoFHRORA5gTtTy7CWUbXS+/e1mOsA6a
sQIDAQABo3kwdzAJBgNVHRMEAjAAMAsGA1UdDwQEAwIFoDATBgNVHSUEDDAKBggr
BgEFBQcDATApBgNVHREEIjAgghJjb3JlLXNlcnZpY2UubG9jYWyHBAoAAL+HBH8A
AAEwHQYDVR0OBBYEFMmx/bnSH6Zpv1lsjJBtsnA8RpSaMA0GCSqGSIb3DQEBCwUA
A4IBAQBzc0rHvCfezgvx1UIEibaze3iMBnM0H5GnP7yiTA7QHbXOla653TrFpBEs
otozyonvYYAnr384S0qQ8V/+icUNPYwNKLhk1QinF4EvZpDu/5JPZJp/0ofTmLyw
2DMxjahhJ3+n5CEWKe3vGEZ7dEzVIWWCMXGxQV81TdFy+dTP8PeT8/X/CxdctdCv
L9812gs4NHEMpVIn081gZjA+sznAstf8uAab6mOZcm5Ut7dLTBQMm2ZdezuBUqnJ
0lUplKLyeUnQ7a0jY9ifoVno1Q37d6GF3Z04sqsfWhIeVEbMFKIky+Oe70S2b9gb
OMNkPPoqrfV6Z2tXF8MQBiNCDEkl
-----END CERTIFICATE-----
`,

  // config name
  CONFIG_NAME: "prod",

  // for test
  VPN_IP: "13.208.47.166",

  // old params for api path check : g_urls
  TABLE_LIST_WHITE_LIST: {
    "/game/tablelist/": ["thirdpartycode"],
    "/log/get/": ["roundid"],
    "/log/ticket/get": ["ticketid"],
    "/transfer/balance/": ["userid"],
    "/transfer/balance/all/": [],
    "/transfer/op_balance/": [],
    "/transfer/in/": ["userid", "amount"],
    "/transfer/out/": ["userid", "amount"],
    "/transfer/betlimit/": [],
    "/cp_transfer/status/list/": ["opkey", "thirdpartycode"],
    // "/bt/"
  },

  // gRPC Error Reponse msg
  GRPC_RES_STATUS_MAP: {
    PROVIDER: {
      EVO: "EVOLUTION",
      BNG: "BNG",
      PP: "PP",
      FASTSPIN: "FASTSPIN",
    },
    EVOLUTION: { ...EvolutionGameStatus },
    BNG: { ...BngGameStatus },
    PP: {},
    FASTSPIN: { ...FastSpinGameStatus },
  },

  DEVICE: {
    pc: "PC",
    mobile: "MOBILE",
  },

  // *todo move to access.code.enum ; global role.
  // Evolition : refId check redis prefix
  EVOLUTION_DEBIT_CHECK_PREFIX: "ev-r_", // ev-r_{refId} : any
  EVOLUTION_DEBIT_CHECK_INIT: { isEnd: false, changeBy: "" },
  EVOLUTION_PRE_CANCEL_PREFIX: "ev-cn_", // ev-cn_{refId}_{id} : sid
  FASTSPIN_DEBIT_TRANSFER_PREFIX: "fs-tra_", // fs-r_{transferId} : transferId
  FASTSPIN_DEBIT_REFERENCE_PREFIX: "fs-ref_", // fs-cn_{referenceId}: referenceId
};

export const MysqlConfig = {
  host: "10.0.0.51",
  port: 33066,
  user: "cx_new_prod_user_a",
  password: "asdqwe123!@#!",
  database: "operator_db",
  waitForConnections: true,
  connectionLimit: 10, // 連線池大小
  queueLimit: 0, // 無上限佇列
  // timezone: 'KST',           // 設定時區
  // dateStrings: true,       // 要以字串拿 datetime/decimal 可開
};
