const INTENT_CLASSIFIER = {
    FAQ: 'FAQ',
    PERSONAL_INFO_QUERY: 'PERSONAL_INFO_QUERY',
    ACTION_REQUEST: 'ACTION_REQUEST',
    COMPLAINT: 'COMPLAINT',
    CHITCHAT: 'CHITCHAT',
    EMERGENCY_INCIDENT: 'EMERGENCY_INCIDENT',
    UNKNOWN: 'UNKNOWN'
}

export { INTENT_CLASSIFIER }
